name: CI

on:
  push:
  pull_request:

jobs:
  deploy:
    # strategy:
    #   fail-fast: false
    #   matrix:
    #     env: 
    #       - dev
    #       - preprod
    #       - prod

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0

      - uses: container-tools/kind-action@fdfd7e7ffb39e532f9de844dba8f1a29ae7e0f75 # renovate: tag=v1.7.0
        timeout-minutes: 5
        with: 
          kubectl_version: v1.22.2
          registry: false
          
      - name: Install kyverno
        run: |
          kubectl apply --wait -k github.com/kyverno/kyverno/config
          sleep 5
          kubectl wait --for=condition=available --timeout=600s -n kyverno deployment/kyverno

      - name: Test
        # if: matrix.env == 'dev'
        run: |
          kubectl apply -k "github.com/example-policy-org/policy/kubernetes/kyverno?ref=1.0.0"
          kubectl apply -k "github.com/example-policy-org/policy/kubernetes/kyverno?ref=2.0.0"
          kubectl apply -k "github.com/example-policy-org/policy/kubernetes/kyverno?ref=2.0.1"
          while [[ $(kubectl get -k "github.com/example-policy-org/policy/kubernetes/kyverno?ref=1.0.0" -o 'jsonpath={..status.ready}') != "true" ]]; do sleep 1; done
          while [[ $(kubectl get -k "github.com/example-policy-org/policy/kubernetes/kyverno?ref=2.0.0" -o 'jsonpath={..status.ready}') != "true true" ]]; do sleep 1; done
          while [[ $(kubectl get -k "github.com/example-policy-org/policy/kubernetes/kyverno?ref=2.0.1" -o 'jsonpath={..status.ready}') != "true true" ]]; do sleep 1; done

          kubectl apply -k github.com/example-policy-org/app1
          kubectl apply -k github.com/example-policy-org/app2
          kubectl apply -k github.com/example-policy-org/app3

          kubectl wait --for=condition=available --timeout=600s deployment/app1 deployment/app2 deployment/app3
